name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build_release:
    name: Build Release ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - name: Run Linux Build
        if: matrix.os == 'ubuntu'
        run: |
          mkdir -p bin
          chmod 755 bin
          docker run -d --name alpine -v $(pwd):/workspace -w /workspace crystallang/crystal:latest-alpine tail -f /dev/null
          docker exec alpine shards install --without-development --release --static
          docker exec alpine shards build --release --static
          docker exec alpine chmod +x bin/cowsay
          docker exec alpine gzip bin/cowsay
          docker exec alpine mv bin/cowsay.gz bin/cowsay-linux.gz

      - name: Run Mac Build x64
        if: matrix.os == 'macos'
        run: |
          shards install --without-development --release
          shards build --release
          chmod +x bin/cowsay
          gzip bin/cowsay
          mv bin/cowsay.gz bin/cowsay-macos.gz

      - name: Run Windows Build x64
        if: matrix.os == 'windows'
        run: |
          shards install --without-development --release
          shards build --release --static
          Set-ExecutionPolicy RemoteSigned -Scope Process
          Compress-Archive -Path bin/cowsay.exe -DestinationPath bin/cowsay-windows.zip

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/cowsay-linux.gz
            bin/cowsay-macos.gz
            bin/cowsay-windows.zip
            LICENSE.txt
